# Site settings
title: Qasim Sudais blog
email: 
description: "Sharing what I learn and find interesting."
baseurl: ""
url: "http://sudais.github.io"
twitter_username: kasim_sudais
github_username:  kasim23

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
